language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y nano

install: 
  - pip install . pytest mock codecov==1.5.1 behave pexpect==3.3

script:
  - coverage run --source pgcli -m py.test
  - cd tests
  - behave

after_success:
  - codecov

notifications:
  webhooks:
    urls:
      - YOUR_WEBHOOK_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

services:
  - postgresql

addons:
  postgresql: "9.3"
